// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "fltkVTKImageViewerGUI.h"

fltkVTKImageViewerGUI::fltkVTKImageViewerGUI() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = externalWindow = new Fl_Double_Window(435, 465);
    w = o;
    o->user_data((void*)(this));
    { vtkFlRenderWindowInteractor* o = fltkRenderWindowInteractor = new vtkFlRenderWindowInteractor(5, 10, 425, 445);
      o->box(FL_DOWN_FRAME);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
      Fl_Group::current()->resizable(o);
    }
    o->end();
  }
}

fltkVTKImageViewerGUI::~fltkVTKImageViewerGUI() {
}

void fltkVTKImageViewerGUI::Show() {
  externalWindow->show();
fltkRenderWindowInteractor->show();
}

void fltkVTKImageViewerGUI::Hide() {
  externalWindow->hide();
}
