// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef fltkDisplayGlWindowFlatGUI_h
#define fltkDisplayGlWindowFlatGUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <fltkGlWindowInteractiveFlat.h>
#include <fltkDrawer.h>

class fltkDisplayGlWindowFlatGUI {
public:
  fltkDisplayGlWindowFlatGUI();
private:
  Fl_Double_Window *parentWindow;
  fltk::GlWindowInteractiveFlat *drawWindow;
public:
  void Show(void);
  void SetLabel(const char *newlabel);
  void Redraw(void);
  void Size(unsigned int nx, unsigned int ny);
  void Hide(void);
  void Update(void);
  int GetWidth(void);
  int GetHeight(void);
  void MakeCurrent(void);
  int IsVisible(void);
  itk::Command * GetRedrawCommand(void);
  itk::Object * GetNotifier(void);
  virtual fltk::GlWindowInteractiveFlat * GetGlWindow(void);
};
#endif
