// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "fltkDisplayGlWindowGUI.h"

fltkDisplayGlWindowGUI::fltkDisplayGlWindowGUI() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = parentWindow = new Fl_Double_Window(640, 480);
    w = o;
    o->user_data((void*)(this));
    { fltk::GlWindowInteractive* o = drawWindow = new fltk::GlWindowInteractive(0, 0, 640, 480);
      o->box(FL_NO_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
      Fl_Group::current()->resizable(o);
    }
    o->end();
  }
}

void fltkDisplayGlWindowGUI::Show(void) {
  parentWindow->show();
drawWindow->show();
}

void fltkDisplayGlWindowGUI::SetLabel(const char *newlabel) {
  parentWindow->label(newlabel);
}

void fltkDisplayGlWindowGUI::Redraw(void) {
  parentWindow->redraw();
drawWindow->redraw();
}

void fltkDisplayGlWindowGUI::Size(unsigned int nx, unsigned int ny) {
  parentWindow->size(nx,ny);
drawWindow->size(nx,ny);
}

void fltkDisplayGlWindowGUI::Hide(void) {
  parentWindow->hide();
}

void fltkDisplayGlWindowGUI::Update(void) {
  Redraw();
}

int fltkDisplayGlWindowGUI::GetWidth(void) {
  return drawWindow->w();
}

int fltkDisplayGlWindowGUI::GetHeight(void) {
  return drawWindow->h();
}

void fltkDisplayGlWindowGUI::MakeCurrent(void) {
  drawWindow->make_current();
}

int fltkDisplayGlWindowGUI::IsVisible(void) {
  return drawWindow->visible_r();
}

fltk::GlWindow::RedrawCommandType * fltkDisplayGlWindowGUI::GetRedrawCommand(void) {
  return drawWindow->GetRedrawCommand();
}

itk::Object * fltkDisplayGlWindowGUI::GetNotifier(void) {
  return drawWindow->GetNotifier();
}

fltk::GlWindowInteractive * fltkDisplayGlWindowGUI::GetGlWindow(void) {
  return drawWindow;
}

void fltkDisplayGlWindowGUI::SaveImage(const char * filename) {
  drawWindow->SaveImage( filename );
}
