// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef fltkTimeProbesCollectorGUI_h
#define fltkTimeProbesCollectorGUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "itkTimeProbesCollectorBase.h"
#include <FL/Fl_Button.H>
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Scroll.H>
#include <FL/Fl_Pack.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Value_Output.H>

class TimeProbesCollectorGUI : public ::itk::TimeProbesCollectorBase {
public:
  TimeProbesCollectorGUI();
  Fl_Double_Window *controlPanel;
private:
  void cb_Close_i(Fl_Button*, void*);
  static void cb_Close(Fl_Button*, void*);
  void cb_Clear_i(Fl_Button*, void*);
  static void cb_Clear(Fl_Button*, void*);
  void cb_Report_i(Fl_Button*, void*);
  static void cb_Report(Fl_Button*, void*);
public:
  Fl_Check_Button *continuousCheckButton;
  Fl_Pack *probesPack;
  Fl_Value_Output *timeResolution;
  virtual ~TimeProbesCollectorGUI();
  virtual void Show(void);
  virtual void Hide(void);
};
#endif
