// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef ImageViewerGUI_h
#define ImageViewerGUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <GLSliceView.h>
#include <FL/Fl_Button.H>
#include <FL/Fl_Value_Slider.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Text_Display.H>
#include <FL/Fl_Browser.H>

class ImageViewerGUI {
public:
  ImageViewerGUI();
  virtual ~ImageViewerGUI();
  Fl_Double_Window* CreateGUI();
  Fl_Double_Window *iviewWindow;
  Fl_Group *glWindowGroup;
private:
  void cb__i(Fl_Button*, void*);
  static void cb_(Fl_Button*, void*);
  void cb_1_i(Fl_Button*, void*);
  static void cb_1(Fl_Button*, void*);
  void cb_2_i(Fl_Button*, void*);
  static void cb_2(Fl_Button*, void*);
  void cb_center_i(Fl_Button*, void*);
  static void cb_center(Fl_Button*, void*);
  void cb_3_i(Fl_Button*, void*);
  static void cb_3(Fl_Button*, void*);
  void cb_4_i(Fl_Button*, void*);
  static void cb_4(Fl_Button*, void*);
  void cb_21_i(Fl_Button*, void*);
  static void cb_21(Fl_Button*, void*);
public:
  Fl_Value_Slider *sliceNumberSlider;
private:
  void cb_sliceNumberSlider_i(Fl_Value_Slider*, void*);
  static void cb_sliceNumberSlider(Fl_Value_Slider*, void*);
  void cb_T_i(Fl_Button*, void*);
  static void cb_T(Fl_Button*, void*);
  void cb_v_i(Fl_Button*, void*);
  static void cb_v(Fl_Button*, void*);
  void cb_d_i(Fl_Button*, void*);
  static void cb_d(Fl_Button*, void*);
  void cb_c_i(Fl_Button*, void*);
  static void cb_c(Fl_Button*, void*);
public:
  Fl_Value_Slider *intensityWindowingMaxSlider;
private:
  void cb_intensityWindowingMaxSlider_i(Fl_Value_Slider*, void*);
  static void cb_intensityWindowingMaxSlider(Fl_Value_Slider*, void*);
public:
  Fl_Value_Slider *intensityWindowingMinSlider;
private:
  void cb_intensityWindowingMinSlider_i(Fl_Value_Slider*, void*);
  static void cb_intensityWindowingMinSlider(Fl_Value_Slider*, void*);
public:
  Fl_Choice *orientationChoice;
private:
  void cb_orientationChoice_i(Fl_Choice*, void*);
  static void cb_orientationChoice(Fl_Choice*, void*);
  static Fl_Menu_Item menu_orientationChoice[];
  void cb_x_i(Fl_Button*, void*);
  static void cb_x(Fl_Button*, void*);
  void cb_y_i(Fl_Button*, void*);
  static void cb_y(Fl_Button*, void*);
  void cb_z_i(Fl_Button*, void*);
  static void cb_z(Fl_Button*, void*);
public:
  Fl_Double_Window *clickedPointsWindow;
  Fl_Browser *clickedPointsBrowser;
private:
  void cb_Update_i(Fl_Button*, void*);
  static void cb_Update(Fl_Button*, void*);
  void cb_Clear_i(Fl_Button*, void*);
  static void cb_Clear(Fl_Button*, void*);
  void cb_Close_i(Fl_Button*, void*);
  static void cb_Close(Fl_Button*, void*);
public:
  Fl_Double_Window *overlayOpacityControlWindow;
private:
  void cb_Close1_i(Fl_Button*, void*);
  static void cb_Close1(Fl_Button*, void*);
public:
  Fl_Value_Slider *overlayOpacitySlider;
private:
  void cb_overlayOpacitySlider_i(Fl_Value_Slider*, void*);
  static void cb_overlayOpacitySlider(Fl_Value_Slider*, void*);
public:
  virtual void CreateGLSliceView( Fl_Group *,Fl_Gl_Window * w );
  virtual void AddMenuBarOptions(void);
  virtual void AddFilterMenuOptions();
  virtual void AddFileMenuOptions();
  virtual void SetImage( itk::ImageBase<3> * img );
  virtual void Show(void);
  virtual void Hide(void);
  virtual void Update(void);
  virtual void Synchronize(void);
  virtual void ImageMode(itk::ImageModeType mode);
  virtual void SelectSlice(unsigned int);
  virtual void SetIntensityWindowingMin(float);
  virtual void SetIntensityWindowingMax(float);
  virtual void CenterWindow(void);
  virtual void ZoomIn(void);
  virtual void ZoomOut(void);
  virtual void ShiftUp(void);
  virtual void ShiftDown(void);
  virtual void ShiftLeft(void);
  virtual void ShiftRight(void);
  virtual void SetOrientation(void);
  virtual void ShowClickedPointsWindow(void);
  virtual void ClearClickedPoints(void);
  virtual void ShowOverlayOpacityControl(void);
  virtual void SetOverlayOpacity(float);
  virtual void UpdateClickedPoints();
  virtual void ViewDetails(bool);
  virtual void ViewValue(bool);
  virtual void ViewCrosshairs(bool);
  virtual bool viewCrosshairs(void);
  virtual bool viewValue(void);
  virtual bool viewDetails(void);
  virtual bool flipX(void);
  virtual void flipX(bool);
  virtual bool flipY(void);
  virtual void flipY(bool);
  virtual bool flipZ(void);
  virtual void flipZ(bool);
};
#endif
