// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "fltkDisplayGlWindowFlatGUI.h"

fltkDisplayGlWindowFlatGUI::fltkDisplayGlWindowFlatGUI() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = parentWindow = new Fl_Double_Window(640, 480);
    w = o;
    o->user_data((void*)(this));
    { fltk::GlWindowInteractiveFlat* o = drawWindow = new fltk::GlWindowInteractiveFlat(0, 0, 640, 480);
      o->box(FL_NO_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
      Fl_Group::current()->resizable(o);
    }
    o->end();
  }
}

void fltkDisplayGlWindowFlatGUI::Show(void) {
  parentWindow->show();
drawWindow->show();
}

void fltkDisplayGlWindowFlatGUI::SetLabel(const char *newlabel) {
  parentWindow->label(newlabel);
}

void fltkDisplayGlWindowFlatGUI::Redraw(void) {
  parentWindow->redraw();
drawWindow->redraw();
}

void fltkDisplayGlWindowFlatGUI::Size(unsigned int nx, unsigned int ny) {
  parentWindow->size(nx,ny);
drawWindow->size(nx,ny);
}

void fltkDisplayGlWindowFlatGUI::Hide(void) {
  parentWindow->hide();
}

void fltkDisplayGlWindowFlatGUI::Update(void) {
  Redraw();
}

int fltkDisplayGlWindowFlatGUI::GetWidth(void) {
  return drawWindow->w();
}

int fltkDisplayGlWindowFlatGUI::GetHeight(void) {
  return drawWindow->h();
}

void fltkDisplayGlWindowFlatGUI::MakeCurrent(void) {
  drawWindow->make_current();
}

int fltkDisplayGlWindowFlatGUI::IsVisible(void) {
  return drawWindow->visible_r();
}

itk::Command * fltkDisplayGlWindowFlatGUI::GetRedrawCommand(void) {
  return drawWindow->GetRedrawCommand();
}

itk::Object * fltkDisplayGlWindowFlatGUI::GetNotifier(void) {
  return drawWindow->GetNotifier();
}

fltk::GlWindowInteractiveFlat * fltkDisplayGlWindowFlatGUI::GetGlWindow(void) {
  return drawWindow;
}
