// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "fltkImage2DViewerGUI.h"

void fltkImage2DViewerGUI::cb_minimumSlider_i(Fl_Value_Slider*, void*) {
  this->RenderImage( minimumSlider->value(), maximumSlider->value() );
}
void fltkImage2DViewerGUI::cb_minimumSlider(Fl_Value_Slider* o, void* v) {
  ((fltkImage2DViewerGUI*)(o->parent()->user_data()))->cb_minimumSlider_i(o,v);
}

void fltkImage2DViewerGUI::cb_maximumSlider_i(Fl_Value_Slider*, void*) {
  this->RenderImage( minimumSlider->value(), maximumSlider->value() );
}
void fltkImage2DViewerGUI::cb_maximumSlider(Fl_Value_Slider* o, void* v) {
  ((fltkImage2DViewerGUI*)(o->parent()->user_data()))->cb_maximumSlider_i(o,v);
}

fltkImage2DViewerGUI::fltkImage2DViewerGUI() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = externalWindow = new Fl_Double_Window(450, 365);
    w = o;
    o->user_data((void*)(this));
    { fltk::Image2DViewerWindow* o = imageViewer = new fltk::Image2DViewerWindow(0, 0, 450, 365);
      o->box(FL_NO_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->align(FL_ALIGN_CENTER);
      o->when(FL_WHEN_RELEASE);
    }
    o->end();
    o->resizable(o);
  }
  { Fl_Double_Window* o = intensityWindow = new Fl_Double_Window(501, 52, "Intensity Windowing");
    w = o;
    o->user_data((void*)(this));
    { Fl_Value_Slider* o = minimumSlider = new Fl_Value_Slider(33, 7, 460, 16, "Min ");
      o->type(1);
      o->labelsize(12);
      o->step(0.01);
      o->callback((Fl_Callback*)cb_minimumSlider);
      o->align(FL_ALIGN_LEFT);
    }
    { Fl_Value_Slider* o = maximumSlider = new Fl_Value_Slider(33, 24, 460, 17, "Max ");
      o->type(1);
      o->labelsize(12);
      o->step(0.01);
      o->callback((Fl_Callback*)cb_maximumSlider);
      o->align(FL_ALIGN_LEFT);
    }
    o->end();
  }
}

fltkImage2DViewerGUI::~fltkImage2DViewerGUI() {
}

void fltkImage2DViewerGUI::SetLabel(const char *label) {
  externalWindow->label( label );
}

void fltkImage2DViewerGUI::Show(void) {
  externalWindow->show();
imageViewer->show();
}

void fltkImage2DViewerGUI::Hide(void) {
  externalWindow->hide();
intensityWindow->hide();
}

void fltkImage2DViewerGUI::Redraw(void) {
  imageViewer->redraw();
Fl::check();
}

void fltkImage2DViewerGUI::Update(void) {
}

void fltkImage2DViewerGUI::RenderImage( double min, double max ) {
}
